### ISSUE TITLE
Removed files

### ISSUE THREAD

**Issue by charles-d-burton** [micahwedemeyer/gphoto2go#3]
Is there an interface in the gphoto2 lib to also remove files?

**Comment by benhinchley** [comment]
`libgphoto2` provides the [`gp_filesystem_delete_file`](http://gphoto.org/doc/api/gphoto2-filesys_8h.html#a4d1424f4d45018dc892a2da792822f0c) function which could be wrapped to provide the ability to delete files

**Comment by charles-d-burton** [comment]
I forked the repo and I'm adding a couple more functions.  I also discovered that on a Nikon 90D the Trigger doesn't return a file.  I added another function to force a capture that I'm testing right now.

**Comment by benhinchley** [comment]
Going to close this, just merged #4
